spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3308/KKANBUFS
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

