spring:
  datasource:
    url: jdbc:mariadb://${DB_url}:${DB_port}/${DB_dataBaseName}?
    username: ${DB_name}
    password: ${DB_password}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

