### 학생 회원가입

POST http://localhost:8080/auth/student/signup
Content-Type: application/json

{
  "name": "김동혁",
  "loginId": "userid1",
  "password": "1234",
  "studentUnm": "20191769",
  "college": "이공대",
  "dept": "컴퓨터공학과",
  "phoneNum": "010-67687-7657",
  "sex": true
}

### 단대 회원가입

POST http://localhost:8080/auth/college/signup
Content-Type: application/json

{
  "name": "이공대",
  "loginId": "college1",
  "password": "1234",
  "instagram": "이공대 인스타 주소"
}

### 업체 회원가입
POST http://localhost:8080/auth/partner/signup
Content-Type: application/json

{
  "name": "역전할머니맥주",
  "loginId": "partner1",
  "password": "1234",
  "partnerType": "요식업",
  "partnerNum": "051-0000-0000",
  "city": "부산시",
  "address1": "모분재로 7번 가길 21",
  "address2": "2층"
}



### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "loginId": "college1",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Cookie:  SESSION=3f7e45ea-d7b1-4efc-9e1b-84e3234e96e4
 //로그인시 항상 갱신됨